name       : freeciv
version    : 2.5.10
release    : 12
source     :
    - http://files.freeciv.org/stable/freeciv-2.5.10.tar.bz2 : c8a14156562dce2f0a7b96390c2d5a35314f1124c448782a6a47b0c51cfcb302
license    : GPL-2.0
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization.
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
