name       : freeciv
version    : 3.0.8
release    : 34
source     :
    - https://github.com/freeciv/freeciv/archive/R3_0_8.tar.gz : a0fa212a675f5469f66d407c09ed72567a7d4ce0ed4ae6d07392e6cd12bcb7cf
license    : GPL-2.0-or-later
homepage   : https://www.freeciv.org/
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(bzip2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %autogen
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-sdl-mixer=sdl2 \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
