name       : freeciv
version    : 2.6.1
release    : 16
source     :
    - https://github.com/freeciv/freeciv/archive/R2_6_1.tar.gz : 9d9c1c63beaa2995c3f807af2b73d5f1d08772caf0f94fbae09e48f6cc94bfec
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %autogen
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
