name       : freeciv
version    : 2.5.4
release    : 1
source     :
    - http://download.gna.org/freeciv/stable/freeciv-2.5.4.tar.bz2 : 9e64ef047fd0d2f8e9aa1da01586dea7cfe63a36b15875c168ada555c2e6634b
license    : GPL-2.0
component  : gaming
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization.
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(atk)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-static \
        --disable-sdltest \
        --disable-sdl2test \
        --enable-client=gtk3 \
        --enable-gcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
