name       : freeciv
version    : 2.5.7
release    : 8
source     :
    - https://netix.dl.sourceforge.net/project/freeciv/Freeciv%202.5/2.5.7/freeciv-2.5.7.tar.bz2 : ffe36736db6a64893681e9eea8b90f7abe05eaebe6b777e82149a98cad6dbed2
license    : GPL-2.0
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization.
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(SDL_mixer)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %configure --disable-static \
        --disable-sdltest \
        --disable-sdl2test \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-sdl-mixer \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
