name       : freeciv
version    : 2.5.8
release    : 9
source     :
    - https://netix.dl.sourceforge.net/project/freeciv/Freeciv%202.5/2.5.8/freeciv-2.5.8.tar.bz2 : 6781e655c514d0a86975c87235de24f740cbdf81f33711d68a910b360963bd30
license    : GPL-2.0
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization.
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(SDL_mixer)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %configure --disable-static \
        --disable-sdltest \
        --disable-sdl2test \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-sdl-mixer \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
