name       : freeciv
version    : 2.5.5
release    : 4
source     :
    - http://download.gna.org/freeciv/stable/freeciv-2.5.5.tar.bz2 : 5622f2142637057f7e47b1eda764c4e131222fab4d5bb42cd59fbd58ba3db1d4
license    : GPL-2.0
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization.
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(atk)
    - pkgconfig(gthread-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(pango)
    - pkgconfig(sqlite3)
setup      : |
    %configure --disable-static \
        --disable-sdltest \
        --disable-sdl2test \
        --enable-client=gtk3 \
        --enable-gcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
