name       : freeciv
version    : 2.6.0
release    : 14
source     :
    - http://files.freeciv.org/stable/freeciv-2.6.0.tar.bz2 : 7c20399198d6c7d846fed9a69b02e01134ae5340a3ae0f99d1e38063ade6c999
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
