name       : freeciv
version    : 3.0.2
release    : 25
source     :
    - https://github.com/freeciv/freeciv/archive/R3_0_2.tar.gz : d87c4c9af72b2eb39aabc09225a40f5a84eeefdb2bdd90bbbf9b829fd5f35537
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %autogen
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-sdl-mixer=sdl2 \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
