name       : freeciv
version    : 2.6.2
release    : 17
source     :
    - https://github.com/freeciv/freeciv/archive/R2_6_2.tar.gz : da3569f4e04a25c28010e0946640f73eff6010d781fbf96d8636a6a37a320fb3
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %autogen
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
