name       : freeciv
version    : 2.5.9
release    : 11
source     :
    - https://netix.dl.sourceforge.net/project/freeciv/Freeciv%202.5/2.5.9/freeciv-2.5.9.tar.bz2 : b83c73585ae80898b27379984f936591b51422c9caccb94880fa16030c975928
license    : GPL-2.0
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history
    of human civilization.
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
