name       : freeciv
version    : 2.6.5
release    : 20
source     :
    - https://github.com/freeciv/freeciv/archive/R2_6_5.tar.gz : 3dd4ad440997139ca2e9028dc94452183a9cabe652ca431353223019af776e05
license    : GPL-2.0-or-later
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - bzip2-devel
setup      : |
    %autogen
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-sdl-mixer=sdl2 \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
